apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ngnix
  name: simpleapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleapp
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
        resources: {}
status: {}
