apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ngnix_deployment
  name: simpleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngnix
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngnix
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
        resources: {}
status: {}
