apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"ngnix"},"name":"ngnix","namespace":"mynamespace"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"ngnix"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"ngnix"}},"spec":{"containers":[{"image":"nginx:1.18.0","name":"nginx","resources":{}}]}}},"status":{}}
  creationTimestamp: "2024-05-08T14:26:16Z"
  generation: 3
  labels:
    app: ngnix
  name: ngnix
  namespace: mynamespace
  resourceVersion: "61504"
  uid: fcdc3ab4-5cd5-4a9f-aae5-b1eab430a07d
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngnix
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngnix
    spec:
      containers:
      - image: nginx:1.19.0
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
