apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-dynamic
  namespace: mynamespace
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # almeno 5GB