apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-dynamic
  namespace: mynamespace
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  claimRef:
    name: my-pvc-dynamic
    namespace: mynamespace
  local:
    path: "/mnt/disk/vol1"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-course-01-worker