# a differenza di quanto fatto con le config-map
# qui usiamo il metodo di passare i secret mediante un file montato in un volume.
# ovviamente è solo per esercizio perché potremmo fare esattamente come fatto con le config-map
# cioè passare il secret mediante le var-env
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts: # definiamo il mount di un volumen
      - name: vol-secret #specificando il nome del volume da montare. Nota che questo nome coincide con quello messo nel "volumes:"
        mountPath: /etc/foo # definiamo il percorso di dove montare il volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  # montiamo un volume
  volumes:
    - name: vol-secret # nome del volume
      secret: # tipologia del volume
        secretName: mysecret #nome del secret definito attraverso il file "mysecret.yaml"
status: {}
