apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simpleapp02
  name: simpleapp02
  namespace: mynamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp02
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleapp02
    spec:
      containers:
      - image: dgkanatsios/simpleapp
        name: simpleapp
        resources: {}
status: {}
